### ISSUE TITLE
username dan password

### ISSUE THREAD

**Issue by doniaries** [yohan20-coder/Sistem-Informasi-Monitoring-Dan-Disposisi-Surat-Masuk#1]
username dan passwordnya bang?? mau coba aplikasinya yang mantap..saya cek di mysql tidak ada tabel nipnya

**Comment by doniaries** [comment]
saya sudah berhasil login

**Comment by yohan20-coder** [comment]
NIP/email : ***@***.***
Password: 123

Coba pake itu

Pada tanggal Sen, 5 Sep 2022 17.31, doniaries ***@***.***>
menulis:

**Comment by doniaries** [comment]
terima kasih bang...aplikasi nya maknyoss!!

**Comment by yohan20-coder** [comment]
Kalau boleh tahu masnya dari mana ni ?

Pada tanggal Sen, 5 Sep 2022 17.50, doniaries ***@***.***>
menulis:
